version: '3'
volumes:
  dist:
services:  

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - './data:/data'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 4200:4200
    networks:
      - webnet

networks:
  webnet:
    driver: bridge