version: '3'
volumes:
  dist:
services:  

  db:
    image: postgres
    restart: always
    volumes:
      - './data:/data'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: b4tataassada
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 0420:0420
    networks:
      - webnet

networks:
  webnet:
    driver: bridge